-- Insert test news articles with correct schema
INSERT INTO news_articles (title, summary, url, category, language, published_at, created_at) VALUES
('YouTube新機能「コミュニティノート」が日本でも利用可能に', 
'YouTubeが誤情報対策として導入したコミュニティノート機能が、ついに日本でも利用できるようになりました。この機能により、ユーザーは動画に対して文脈情報を追加できるようになります。',
'https://akagami.net/news/youtube-community-notes',
'YouTube',
'ja',
datetime('now', '-2 hours'),
datetime('now', '-2 hours')),

('Instagram、新しいアルゴリズム変更を発表 - リール動画が優遇', 
'Instagramが最新のアルゴリズム変更を発表。リール動画コンテンツがフィード表示においてより優遇されることになります。静止画投稿と比較して、リール動画は最大3倍のリーチが期待できます。',
'https://akagami.net/news/instagram-algorithm-update',
'Instagram',
'ja',
datetime('now', '-5 hours'),
datetime('now', '-5 hours')),

('TikTok、18分の長尺動画に対応へ - YouTubeとの競争激化', 
'TikTokが最大18分の長尺動画に対応することを発表。この変更により、より詳細なコンテンツや教育的な動画の投稿が可能になります。YouTubeとの競争がさらに激化しています。',
'https://akagami.net/news/tiktok-18-minutes',
'TikTok',
'ja',
datetime('now', '-8 hours'),
datetime('now', '-8 hours')),

('生成AI「GPT-5」のリリース時期が明らかに - OpenAI CEO発言', 
'OpenAIのサム・アルトマンCEOが、次世代AI「GPT-5」について言及。GPT-5は2024年後半にリリース予定で、推論能力と文脈理解の精度が大幅に向上するとのことです。',
'https://akagami.net/news/gpt5-release',
'生成AI',
'ja',
datetime('now', '-1 day'),
datetime('now', '-1 day')),

('Threads、広告機能のテストを開始 - 収益化への第一歩', 
'Metaの新SNS「Threads」が、限定的に広告機能のテストを開始。現在はアメリカとカナダの一部ユーザーにのみ広告が表示されており、収益化に向けた重要なステップとして注目されています。',
'https://akagami.net/news/threads-ads-test',
'Threads',
'ja',
datetime('now', '-1 day'),
datetime('now', '-1 day')),

('YouTube、クリエイター向け新しい収益化プログラムを発表', 
'YouTubeが小規模クリエイター向けの新しい収益化プログラムを発表。従来は1000人の登録者が必要でしたが、新プログラムでは500人から参加可能になります。',
'https://akagami.net/news/youtube-monetization',
'YouTube',
'ja',
datetime('now', '-2 days'),
datetime('now', '-2 days')),

('Instagram、ストーリーズに新しいスタンプ機能を追加', 
'Instagramがストーリーズに新しいインタラクティブなスタンプ機能を追加。ユーザーのエンゲージメント向上が期待されています。',
'https://akagami.net/news/instagram-new-stickers',
'Instagram',
'ja',
datetime('now', '-3 days'),
datetime('now', '-3 days')),

('TikTok、ライブ配信機能を大幅アップデート', 
'TikTokがライブ配信機能を大幅にアップデート。新しいエフェクトやギフト機能が追加され、クリエイターの収益化がさらに促進されます。',
'https://akagami.net/news/tiktok-live-update',
'TikTok',
'ja',
datetime('now', '-3 days'),
datetime('now', '-3 days'));
