-- Insert test news articles
INSERT INTO news_articles (title, excerpt, content, image_url, category, tags, author, published_at, created_at) VALUES
('YouTube新機能「コミュニティノート」が日本でも利用可能に', 
'YouTubeが誤情報対策として導入したコミュニティノート機能が、ついに日本でも利用できるようになりました。', 
'<p>YouTubeは2024年1月15日、誤情報対策として導入した「コミュニティノート」機能を日本でも利用可能にしたと発表しました。</p><p>この機能により、ユーザーは動画に対して文脈情報を追加できるようになり、より正確な情報の共有が可能になります。</p><p>コミュニティノートは、X（旧Twitter）で導入されているものと同様の仕組みで、複数のユーザーによる評価を経て表示されます。</p>',
'/news-placeholder.jpg',
'YouTube',
'YouTube,新機能,誤情報対策',
'Akagami編集部',
datetime('now', '-2 hours'),
datetime('now', '-2 hours')),

('Instagram、新しいアルゴリズム変更を発表 - リール動画が優遇', 
'Instagramが最新のアルゴリズム変更を発表。リール動画コンテンツがより優遇されることが明らかになりました。', 
'<p>Meta社は2024年1月15日、Instagramのアルゴリズムに関する重要な変更を発表しました。</p><p>今回の変更により、リール動画コンテンツがフィード表示においてより優遇されることになります。</p><p>静止画投稿と比較して、リール動画は最大3倍のリーチが期待できるとのことです。</p><p>クリエイターやマーケターは、この変更に対応したコンテンツ戦略の見直しが必要になります。</p>',
'/news-placeholder.jpg',
'Instagram',
'Instagram,アルゴリズム,リール',
'Akagami編集部',
datetime('now', '-5 hours'),
datetime('now', '-5 hours')),

('TikTok、18分の長尺動画に対応へ - YouTubeとの競争激化', 
'TikTokが最大18分の長尺動画に対応することを発表。YouTubeとの競争がさらに激化しています。', 
'<p>TikTokは2024年1月14日、これまで10分だった動画の最大長を18分に拡大すると発表しました。</p><p>この変更により、より詳細なコンテンツや教育的な動画の投稿が可能になります。</p><p>業界専門家は、この動きをYouTubeへの対抗策と分析しています。</p><p>クリエイターにとっては、より多様なコンテンツ制作の機会が広がることになります。</p>',
'/news-placeholder.jpg',
'TikTok',
'TikTok,動画,YouTube',
'Akagami編集部',
datetime('now', '-8 hours'),
datetime('now', '-8 hours')),

('生成AI「GPT-5」のリリース時期が明らかに - OpenAI CEO発言', 
'OpenAIのサム・アルトマンCEOが、次世代AI「GPT-5」のリリース時期について言及しました。', 
'<p>OpenAIのサム・アルトマンCEOは、最新のインタビューで次世代AI「GPT-5」について語りました。</p><p>GPT-5は2024年後半にリリース予定で、現在のGPT-4と比較して大幅な性能向上が期待されています。</p><p>特に、推論能力と文脈理解の精度が向上し、より人間に近い対話が可能になるとのことです。</p><p>マーケティング業界への影響も大きく、コンテンツ制作の効率化がさらに進むと予想されています。</p>',
'/news-placeholder.jpg',
'生成AI',
'生成AI,ChatGPT,OpenAI',
'Akagami編集部',
datetime('now', '-1 day'),
datetime('now', '-1 day')),

('Threads、広告機能のテストを開始 - 収益化への第一歩', 
'Metaの新SNS「Threads」が、限定的に広告機能のテストを開始したことが明らかになりました。', 
'<p>Meta社は2024年1月13日、Threadsでの広告機能テストを一部の地域で開始したと発表しました。</p><p>現在はアメリカとカナダの一部ユーザーにのみ広告が表示されています。</p><p>この動きは、Threadsの収益化に向けた重要なステップとして注目されています。</p><p>マーケターにとっては、新たな広告プラットフォームとして大きなチャンスになる可能性があります。</p>',
'/news-placeholder.jpg',
'Threads',
'Threads,広告,Meta',
'Akagami編集部',
datetime('now', '-1 day'),
datetime('now', '-1 day')),

('YouTube、クリエイター向け新しい収益化プログラムを発表', 
'YouTubeが小規模クリエイター向けの新しい収益化プログラムを発表。参加条件が大幅に緩和されます。', 
'<p>YouTubeは2024年1月12日、新しいクリエイター収益化プログラムを発表しました。</p><p>従来は1000人の登録者が必要でしたが、新プログラムでは500人から参加可能になります。</p><p>また、ショート動画の収益化条件も緩和され、より多くのクリエイターが収益を得られるようになります。</p><p>この変更により、YouTubeクリエイターのすそ野が広がることが期待されています。</p>',
'/news-placeholder.jpg',
'YouTube',
'YouTube,収益化,クリエイター',
'Akagami編集部',
datetime('now', '-2 days'),
datetime('now', '-2 days'));
