#!/bin/bash

echo "================================"
echo "GitHub Push Commands"
echo "================================"
echo ""
echo "プロジェクトディレクトリ: /home/user/webapp"
echo "リモートリポジトリ: https://github.com/gami24/akagami-research.git"
echo "ブランチ: main"
echo ""
echo "--- コマンド ---"
echo ""
echo "cd /home/user/webapp"
echo "git push -u origin main"
echo ""
echo "================================"
echo ""
echo "認証方法:"
echo "1. Personal Access Token を使用"
echo "   - https://github.com/settings/tokens"
echo "   - 'repo' スコープにチェック"
echo "   - トークンを生成してコピー"
echo "   - プッシュ時にパスワードの代わりに貼り付け"
echo ""
echo "2. GitHub CLI を使用（推奨）"
echo "   - gh auth login"
echo "   - ブラウザでログイン"
echo "   - git push -u origin main"
echo ""
echo "================================"
